#alias ld 'eza -lD'
alias lf 'eza -lF --color=always | grep -v /'
alias lh 'eza -dl .* --group-directories-first'
alias ll 'eza -al --group-directories-first'
alias ls 'eza -alF --color=always --sort=size'
alias lsf 'eza -alF --color=always --sort=size | ggrep -v /'
alias lt 'eza -al --sort=modified'
alias la 'eza -la --sort=modified --group-directories-first --colour=always'
